### ISSUE TITLE
문자씨 기능 추가.

### ISSUE THREAD

**Issue by Taebu** [Taebu/safen_point#9]
선행 조건 케시-큐에 가맹점 코드를 추가한 후, 
템플릿 코드 값을 추가한 후 진행한다.

**Comment by Taebu** [comment]
#402 가맹점 코드 추가 #403
https://github.com/Taebu/cashq/issues/403

문자씨 템플릿 관리 #404 
https://github.com/Taebu/cashq/issues/404

완료 문자씨 java 소스에 추가 할것.

code|comment
--|--
code_3023|MUNJA-C 사용여부 YN
code_3024|MUNJA-C.rid (MMS발송할 핸드폰번호)
mj_mid|MUNJA-C.mid (발송할 문자 태그번호)

**Comment by Taebu** [comment]
```java
Map<String, String> codes = new HashMap<String, String>();

codes = get_codes(st_no);

/**
 *  코드 정보들 가져오기
 *
 * @author Taebu Moon <mtaebu@gmail.com>
 * @param string $st_no  상점아이디
 * @return codes 코드 값
 */
private static Map<String, String> get_codes(String st_no)
{

	String sql="";
	Map<String, String> codes = new HashMap<String, String>();
	
	MyDataObject dao = new MyDataObject();		
	
	sql="select ";
	sql+="pv_code, ";
	sql+="pv_value ";
	sql+="from ";
	sql+="prq_values ";
	sql+="where pv_no='"+st_no+"';";

	try {
		dao.openPstmt(sql);
		dao.setRs(dao.pstmt().executeQuery());
		while(dao.rs().next()){
		codes.put("code_"+dao.rs().getString("pv_code"), dao.rs().getString("pv_value"));
		}
	} catch (SQLException e) {
		Utils.getLogger().warning(e.getMessage());
		DBConn.latest_warning = "ErrPOS021";
		e.printStackTrace();
	}
	catch (Exception e) {
		Utils.getLogger().warning(e.getMessage());
		Utils.getLogger().warning(Utils.stack(e));
		DBConn.latest_warning = "ErrPOS022";
	}
	finally {
		dao.closePstmt();
	}
	return codes;
}
```
ㅊㅜㄱㅏ

**Comment by Taebu** [comment]
10월 18, 2019 2:45:04 오후 kr.co.cashq.safen_point.Safen_cmd_queue set_site_push_log
WARNING: Data truncation: Data too long for column 'stype' at row 1
10월 18, 2019 2:45:04 오후 kr.co.cashq.safen_point.Safen_cmd_queue set_site_push_log
WARNING: com.mysql.jdbc.MysqlDataTruncation: Data truncation: Data too long for column 'stype' at row 1
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3833)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3771)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2435)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2582)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2535)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1911)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2145)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2081)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2066)
	at kr.co.cashq.safen_point.Safen_cmd_queue.set_site_push_log(Safen_cmd_queue.java:536)
	at kr.co.cashq.safen_point.Safen_cmd_queue.doMainProcess(Safen_cmd_queue.java:381)
	at kr.co.cashq.safen_point.SAFEN_POINT.doWork(SAFEN_POINT.java:240)
	at kr.co.cashq.safen_point.SAFEN_POINT.doMainProcess(SAFEN_POINT.java:80)
	at kr.co.cashq.safen_point.SAFEN_POINT.main(SAFEN_POINT.java:41)

**Comment by Taebu** [comment]
```sql
ALTER TABLE `cashq`.`site_push_log` 
CHANGE COLUMN `stype` `stype` CHAR(20) NULL DEFAULT 'CAL_SMS' ;
```
